#!/usr/bin/env bash

cd "${BASH_SOURCE%/*}"

tabs -24

[[ $# = 0 ]] && set -- *.m3u

re='#[[:space:]]*Date:'

grep -HZ "$re" "$@" | sed -E 's/^(.*)\x0#[[:space:]]*Date:[[:space:]]*(.*)$/\2\t\1/' | sort
grep -HL "$re" "$@" | sed 's/^/\t&/'
